name: local_llm
services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: always
    volumes:
      - /var/lib/local_llm/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx
    depends_on:
      - open-webui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/local_llm/nginx:/etc/nginx/conf.d
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    depends_on:
      - ollama
      - redis-open-webui
      - searxng
      - docling
      - litellm
      - qdrant
    restart: always
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_WEBSOCKET_SUPPORT: true
      WEBSOCKET_MANAGER: redis
      WEBSOCKET_REDIS_URL: redis://redis-open-webui:6379/0
      CONTENT_EXTRACTION_ENGINE: docling
      VECTOR_STORE: qdrant
      QDRANT_URL: http://qdrant:6333
    volumes:
      - "/var/lib/local_llm/open-webui:/app/backend/data"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  redis-open-webui:
    image: docker.io/valkey/valkey:latest
    container_name: redis-open-webui
    restart: always
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    depends_on:
      - redis-searxng
    restart: always
    volumes:
      - /etc/local_llm/searxng:/etc/searxng
    environment:
      BASE_URL: "http://searxng:8080/"
      SEARXNG_BIND_ADDRESS: 0.0.0.0
      SEARXNG_PORT: 8080
      INSTANCE_NAME: "searxng"
      SEARXNG_REDIS_URL: "redis://redis-searxng:6379/0"
  redis-searxng:
    image: docker.io/valkey/valkey:latest
    container_name: redis-searxng
    restart: always
  docling:
    image: quay.io/docling-project/docling-serve:latest
    container_name: docling
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: always
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    restart: always
    volumes:
      - /etc/local_llm/litellm/litellm.yaml:/app/litellm.yaml
    command: ["--config", "/app/litellm.yaml", "--port", "4000"]
    env_file: /etc/local_llm/litellm/.env
    environment:
      REDIS_HOST: redis-litellm
      REDIS_PORT: 6379
    depends_on:
      - redis-litellm
  redis-litellm:
    image: docker.io/valkey/valkey:latest
    container_name: redis-litellm
    restart: always
  qdrant:
    image: docker.io/qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    volumes:
      - /var/lib/local_llm/qdrant:/qdrant/storage
